device:
  name: "Huion Keydial Mini"
  # address: "AA:BB:CC:DD:EE:FF"  # Optional: uncomment and set specific device address

bluetooth:
  scan_timeout: 10.0
  connection_timeout: 30.0
  reconnect_attempts: 3

uinput:
  device_name: "Huion Keydial Mini"

key_mappings:
  button_1: "KEY_F1"
  button_2: "KEY_F2"
  button_3: "KEY_F3"
  button_4: "KEY_F4"
  button_5: "KEY_F5"
  button_6: "KEY_F6"
  button_7: "KEY_F7"
  button_8: "KEY_F8"
  button_9: "KEY_F9"
  button_10: "KEY_F10"
  button_11: "KEY_F11"
  button_12: "KEY_F12"
  button_13: "KEY_1"
  button_14: "KEY_2"
  button_15: "KEY_3"
  button_16: "KEY_4"
  button_17: "KEY_5"
  button_18: "KEY_6"

dial_settings:
  sensitivity: 1.0
  clockwise_key: "KEY_VOLUMEUP"
  counterclockwise_key: "KEY_VOLUMEDOWN"
  click_key: "KEY_ENTER"
