# Huion Keydial Mini Configuration

device_address: null  # Will auto-discover if not set

key_mappings:
  BUTTON_1: "KEY_F1"
  BUTTON_2: "KEY_LEFTCTRL+KEY_C"
  BUTTON_3: "KEY_A"
  BUTTON_4: "KEY_B"
  BUTTON_5: "KEY_VOLUMEUP"
  BUTTON_6: "KEY_VOLUMEDOWN"
  BUTTON_7: "KEY_ENTER"
  BUTTON_8: "KEY_ESC"

dial_settings:
  clockwise_key: "KEY_RIGHT"
  counterclockwise_key: "KEY_LEFT"
  click_key: "KEY_SPACE"
  sensitivity: 1.0

uinput_device_name: "Huion Keydial Mini"
connection_timeout: 10.0
debug_mode: false
